global:
  scrape_interval: 15s # when Prometheus is pulling data from exporters etc
  evaluation_interval: 30s # time between each evaluation of Prometheus' alerting rules

scrape_configs:
  - job_name: picker
    static_configs:
      - targets:
          - picker:8003
  - job_name: producer
    static_configs:
      - targets:
          - producer:8000
  - job_name: queue
    static_configs:
      - targets:
          - queue:8002
  - job_name: ws-rest
    static_configs:
      - targets:
          - ws-rest:8004
